//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SO.Urba.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomePageContent
    {
        public int ID { get; set; }
        public string Section1 { get; set; }
        public string Section2 { get; set; }
        public string Section3 { get; set; }
        public string Section4 { get; set; }
        public string Section5 { get; set; }
        public string Section6 { get; set; }
        public string FooterSection1 { get; set; }
        public string FooterSection2 { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string PageName { get; set; }
    }
}
